Bug/118 supported actions explaintypes json not considered
Accenture/sfmc-devtools-vscode pull request #129
Opened 2024-02-09 09:48 UTC by anasilva105

# PR details

## What changes did you make? (Give an overview)

- All the menu action (Copy, Deploy and Retrieve) now check if if they are supported in SFMC DevTools according to the following retrieved from the explainTypes command:
     - retrieve -> retrieve
     - deploy -> create || update
     - copy -> create || update
     - copy & deploy --> create || update 

- Notification Message is displayed when one or more metadata types is not supported
- closes #118

2024-02-09 09:59 UTC, JoernBerkefeld commented
Could you Post a Screenshot of the notification that users get  please

2024-02-09 10:03 UTC, anasilva105 commented
> Could you Post a Screenshot of the notification that users get please

Added to the PR

2024-02-09 10:38 UTC, JoernBerkefeld requested changes

2024-02-09 10:38 UTC, JoernBerkefeld commented on src/devtools/main.ts
> +    editorInput.handleShowNotificationMessage("info", mainConfig.messages.unsupportedMetadataType, []);
```suggestion
    editorInput.handleShowNotificationMessage("error", mainConfig.messages.unsupportedMetadataType, []);
```

argument could be made for "warning" but I believe that this should be stronger and hence lean towards "error"

2024-02-09 10:38 UTC, JoernBerkefeld commented on src/devtools/main.ts
> +            "info",
```suggestion
            "error", 
```
should be an error, not info.

2024-02-09 10:59 UTC, anasilva105 commented
@JoernBerkefeld what about the notification displayed should it be an error, warning or info ?

warning
![image](https://github.com/Accenture/sfmc-devtools-vscode/assets/66126240/2f01a894-ab94-48f3-b830-195c01485079)


error:
![image](https://github.com/Accenture/sfmc-devtools-vscode/assets/66126240/0f54b5f8-8844-4eb0-a837-1ac7035e6fd3)


info:
![image](https://github.com/Accenture/sfmc-devtools-vscode/assets/66126240/9df6c7bd-e834-471b-82d6-9aec3cb04f0a)

2024-02-09 11:55 UTC, JoernBerkefeld commented
i assumed my proposed changes would cascade down to that particular pop-up --> error.
that being said. can we do add a "more details" button instead of the directions in sentence #2?

2024-02-09 14:03 UTC, anasilva105 commented
@JoernBerkefeld updated solution to display a More Details button. Clicking on this button will open the extension Output Channel:

![image](https://github.com/Accenture/sfmc-devtools-vscode/assets/66126240/ed6a496e-ab11-4d0e-86b1-3afaf1d925a9)

2024-02-10 16:50 UTC, JoernBerkefeld approved these changes

2024-02-12 08:34 UTC, merged