Bug/159 deploy option does not show up on folders in assetmessages folder
Accenture/sfmc-devtools-vscode pull request #168
Opened 2024-04-24 13:19 UTC by anasilva105

# PR details

## What changes did you make? (Give an overview)

Updated package.json to consider when deploying assets from the retrieve folder to consider all the folder that are inside the specific asset folders (message, block, other, ...)

2024-04-24 17:42 UTC, JoernBerkefeld requested changes

2024-04-24 17:42 UTC, JoernBerkefeld commented on package.json
> +               "when": "resourcePath =~ /retrieve/ && (resourceExtname == '.json' || resourceExtname == '.html' || resourceExtname == '.sql' || resourceExtname == '.ssjs' || resourceLangId == 'markdo
should this also use `resourceDirname =~ /asset\\\\[a-zA-Z]*/)",` ?

2024-04-25 07:41 UTC, anasilva105 commented on package.json
> +               "when": "resourcePath =~ /retrieve/ && (resourceExtname == '.json' || resourceExtname == '.html' || resourceExtname == '.sql' || resourceExtname == '.ssjs' || resourceLangId == 'markdo
No need since this line is related to the menu of the file opened in the editor, not in the explorer tree view. Since you don't open folders in the file editor and I don't think this option is needed

 The issue was related to deploy folders inside the assets folders.

2024-04-25 13:58 UTC, JoernBerkefeld approved these changes

2024-04-30 15:11 UTC, merged